spring.application.name=game-store
spring.datasource.url=jdbc:postgresql://localhost:5432/game-store
spring.datasource.username=postgres
spring.datasource.password=Caramelo05!
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
